// Моковые данные для разработки
// В дальнейшем будут заменены на реальные API запросы

export const mockProducts = [
  {
    id: 1,
    name: 'Мармеладные мишки',
    price: 350,
    image: 'https://avatars.mds.yandex.net/i?id=ef557148f7ae3f9c5a9fa4f7b3cc965fa23b6e59-9025500-images-thumbs&n=13',
    description: 'Классические мармеладные мишки с натуральными фруктовыми вкусами. Идеально подходят для детей и взрослых.',
    taste: 'Ассорти',
    shape: 'Медведи',
    collection: 'Классика',
    sugar: true,
    stock: 50,
    weight: 200, // грамм
  },
  {
    id: 2,
    name: 'Кислые червячки',
    price: 400,
    image: 'https://avatars.mds.yandex.net/get-mpic/12444182/2a0000018ed57b1973fbe579f92e41dc1c7e/orig',
    description: 'Кислые разноцветные червячки с насыщенным фруктовым вкусом. Для любителей кисленького!',
    taste: 'Кислые фрукты',
    shape: 'Червячки',
    collection: 'Кислинка',
    sugar: true,
    stock: 30,
    weight: 200,
  },
  {
    id: 3,
    name: 'Ягодный микс без сахара',
    price: 450,
    image: 'https://avatars.mds.yandex.net/get-mpic/15453732/2a000001982c7927cd4da0fe8a9dc13d0e60/orig',
    description: 'Натуральный мармелад с ягодными вкусами без добавления сахара. На фруктозе.',
    taste: 'Ягоды',
    shape: 'Дольки',
    collection: 'ЗОЖ',
    sugar: false,
    stock: 25,
    weight: 180,
  },
  {
    id: 4,
    name: 'Цитрусовая радуга',
    price: 380,
    image: 'https://avatars.mds.yandex.net/get-mpic/4709279/img_id7003476824287982118.jpeg/orig',
    description: 'Яркие цитрусовые дольки: апельсин, лимон, грейпфрут, лайм.',
    taste: 'Цитрус',
    shape: 'Дольки',
    collection: 'Классика',
    sugar: true,
    stock: 40,
    weight: 200,
  },
  {
    id: 5,
    name: 'Тропический рай',
    price: 480,
    image: 'https://cdn1.ozone.ru/s3/multimedia-1-n/7790575955.jpg',
    description: 'Экзотические тропические вкусы: манго, маракуйя, ананас.',
    taste: 'Тропические фрукты',
    shape: 'Кольца',
    collection: 'Премиум',
    sugar: true,
    stock: 20,
    weight: 220,
  },
  {
    id: 6,
    name: 'Мармелад премиум без сахара',
    price: 550,
    image: 'https://avatars.mds.yandex.net/i?id=aa8a82f522be48f0c3af49dc55417e34_l-7012837-images-thumbs&n=13',
    description: 'Премиальный мармелад на пектине, без сахара. Изысканные вкусы.',
    taste: 'Ассорти',
    shape: 'Фигурки',
    collection: 'Премиум',
    sugar: false,
    stock: 15,
    weight: 250,
  },
];

export const mockOrders = [
  {
    id: '12345',
    userId: 1,
    customer: 'Иван Иванов',
    email: 'ivan@example.com',
    phone: '+7 999 123 45 67',
    date: '2024-12-01T10:30:00',
    status: 'Доставлен',
    total: 1150,
    delivery: 'cdek',
    payment: 'online',
    address: 'Москва, ул. Ленина, д. 10, кв. 5',
    items: [
      { productId: 1, name: 'Мармеладные мишки', quantity: 2, price: 350 },
      { productId: 3, name: 'Ягодный микс без сахара', quantity: 1, price: 450 },
    ],
  },
  {
    id: '12346',
    userId: 2,
    customer: 'Мария Петрова',
    email: 'maria@example.com',
    phone: '+7 999 234 56 78',
    date: '2024-12-03T14:20:00',
    status: 'Отправлен',
    total: 750,
    delivery: 'boxberry',
    payment: 'cash',
    address: 'Санкт-Петербург, Невский пр., д. 50',
    items: [
      { productId: 2, name: 'Кислые червячки', quantity: 1, price: 400 },
      { productId: 4, name: 'Цитрусовая радуга', quantity: 1, price: 380 },
    ],
  },
  {
    id: '12347',
    userId: 1,
    customer: 'Иван Иванов',
    email: 'ivan@example.com',
    phone: '+7 999 123 45 67',
    date: '2024-12-04T09:15:00',
    status: 'Новый',
    total: 1500,
    delivery: 'cdek',
    payment: 'online',
    address: 'Москва, ул. Ленина, д. 10, кв. 5',
    items: [
      { productId: 5, name: 'Тропический рай', quantity: 2, price: 480 },
      { productId: 6, name: 'Мармелад премиум без сахара', quantity: 1, price: 550 },
    ],
  },
];

export const mockUsers = [
  {
    id: 1,
    email: 'user@example.com',
    password: 'password',
    name: 'Иван Иванов',
    role: 'user',
    phone: '+7 999 123 45 67',
  },
  {
    id: 2,
    email: 'admin@marmalade.com',
    password: 'admin',
    name: 'Илья Кузнецов',
    role: 'admin',
    phone: '+7 999 999 99 99',
  },
];